Update 2020-07-02-allow-yourself-to-fail.md
OpenFn/blog pull request #10
Opened 2020-10-19 15:34 UTC by ritazagoni

Edits for clarification

2020-10-20 08:46 UTC, taylordowns2000 requested changes
Looks great, pending the one requested change, re: dash usage.

2020-10-20 08:46 UTC, taylordowns2000 commented on _posts/2020-07-02-allow-yourself-to-fail.md
> +creating S3 (**S**ecure, **S**table and **S**calable - more on that [here](https://openfn.org/trust)) integrations because it provides you with two
Please use an em dash ( — ) here, rather than an en dash ( - ) and please remove the spaces on either side of the em dash.

2020-10-26 13:35 UTC, taylordowns2000 commented
Hey use the compose key on Ubuntu to write an em dash! That's — for the
record :-)

On Mon, Oct 26, 2020 at 1:31 PM Rita Zágoni <notifications@github.com>
wrote:

> @ritazagoni <https://github.com/ritazagoni> requested your review on: #10
> <https://github.com/OpenFn/blog/pull/10> Update
> 2020-07-02-allow-yourself-to-fail.md.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenFn/blog/pull/10#event-3920714517>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACCUBLLUJDTUUSVLB2CWWADSMV223ANCNFSM4SWJ7VEQ>
> .
>

2020-10-26 13:47 UTC, ritazagoni commented
Ha I think I managed it.

2020-10-26 13:48 UTC, merged